title: María Colell
email: hola@mariacolell.com
description: "High quality translation services in the following specializations: law, finance, marketing, audiovisual, and website localization."
baseurl: ""
url: "http://www.mariacolell.com"

markdown: kramdown

sass:
  style: compressed
